### ISSUE TITLE
async function not supprted?

### ISSUE THREAD

**Issue by huwylphi** [nodeca/js-yaml-js-types#3]
I'm try to write async !!js/function like
`data: !!js/function async function () { return await myFunction() }`

or

`data: !!js/function async () => await myFunction()`

but get an exception:
>  SyntaxError: await is only valid in async function

Are async function supported?

**Comment by rlidwka** [comment]
Not supported, see discussion in https://github.com/nodeca/js-yaml/pull/496

The reason is: there is no way to make it work in old browsers, and having a code that can that parses or fails to parse specific yaml depending on a platform code is running on is just a bad idea.

If you need async functions, you can override !!js/function type with something like this:

```diff
6a7,8
> var AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
>
54a57,59
>     if (ast.body[0].expression.async) {
>       return new AsyncFunction(params, source.slice(body[0] + 1, body[1] - 1));
>     }
59a65,67
>   if (ast.body[0].expression.async) {
>     return new AsyncFunction(params, 'return ' + source.slice(body[0], body[1]));
>   }
68c76,77
<   return Object.prototype.toString.call(object) === '[object Function]';
---
>   var type = Object.prototype.toString.call(object);
>   return type === '[object Function]' || type === '[object AsyncFunction]';
```
